#!/bin/bash

function colors {
  GREEN="\e[32m"
  RED="\e[39m"
  NORMAL="\e[0m"
  LMAGENTA='\e[1;35m' 
}

colors

echo -e "${}                                                           ${NORMAL}"                                            
echo -e "${LMAGENTA}  ______    ______     _____                       ${NORMAL}"
echo -e "${LMAGENTA} / _____)  (_____ \   (_____)        _             ${NORMAL}"
echo -e "${LMAGENTA}| /         _____) )     _          | |_     ____  ${NORMAL}"
echo -e "${LMAGENTA}| |        |  ____/     | |         |  _)   |    \ ${NORMAL}"
echo -e "${LMAGENTA}| \_____   | |         _| |_    _   | |__   | | | |${NORMAL}"
echo -e "${LMAGENTA} \______)  |_|        (_____)  (_)   \___)  |_|_|_|${NORMAL}"
                                                   
