#!/bin/bash

function colors {
  GREEN="\e[32m"
  RED="\e[39m"
  NORMAL="\e[0m"
  LMAGENTA='\e[1;35m' 
}

colors




                                                   
echo -e "${}                                         ${NORMAL}"
echo -e "${LMAGENTA}  /$$$$$$  /$$$$$$   /$$   /$$$$$$$$$$$ /$$      /$$ ${NORMAL}"
echo -e "${LMAGENTA} /$$__  $$| $$__ $$ | $$  |___  $$___/ | $$$    /$$$ ${NORMAL}"
echo -e "${LMAGENTA}| $$  \__/| $$  \ $$| $$      | $$     | $$$$  /$$$$ ${NORMAL}"
echo -e "${LMAGENTA}| $$      | $$  | $$| $$      | $$     | $$ $$/$| $$ ${NORMAL}"
echo -e "${LMAGENTA}| $$   /$$| $$$$$$ /| $$      | $$     | $$  $$ | $$ ${NORMAL}"
echo -e "${LMAGENTA}| $$  | $$| $$ __ / | $$      | $$     | $$     | $$ ${NORMAL}"
echo -e "${LMAGENTA}|  $$$$$$/| $$      | $$ /$$  | $$     | $$     | $$ ${NORMAL}"
echo -e "${LMAGENTA} \______/ |__/      |__/ |_/  |__/     |__/     |__/ ${NORMAL}"

